//login
export const SAVE_ERROR_DESCRIPTION = 'SAVE_ERROR_DESCRIPTION'
export const MAKE_LOGIN = 'MAKE_LOGIN'
export const MAKE_LOGOUT = 'MAKE_LOGOUT'

//create
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE'
export const CLEAR_INPUT_VALUE = 'CLEAR_INPUT_VALUE'
export const CHANGE_PLAYLIST_NAME = 'CHANGE_PLAYLIST_NAME'
